### ISSUE TITLE
Bug-fix: NonType Error in .resize()

### ISSUE THREAD

**Issue by nakashimas** [nakashimas/abstragram#2]
## SUMMARY

特定の画像・検索対象でGoogleColorProperty実行時にNoneTypeエラーが出る

## REPRODUCE

検索対象「ドーベルマン窃盗」に含まれていた、破損したpng画像を読み込むことで発生

## ACTUAL RESULTS

問題の箇所とエラーメッセージ

```
INFO: CONVERT
_____ Downloading images for: ドーベルマン窃盗 ...
Traceback (most recent call last):
  File "core.py", line 184, in <module>
    _abs = Abstragram()
  File "core.py", line 68, in __init__
    self.generate_color_picker(self.trends[i], _dir_trend)
  File "core.py", line 108, in generate_color_picker
    _pic = GoogleColorProperty(trend)
  File "\path\to\colorpicker.py", line 132, in __init__
    super().__init__(target_word)
  File "\path\to\colorpicker.py", line 60, in __init__
    self.content = self._convert(content_path) # 画像をリスト化したもの
  File "\path\to\colorpicker.py", line 152, in _convert
    _output += super()._convert(i)
  File "\path\to\colorpicker.py", line 66, in _convert
    _img.resize((_img.shape[0] * _img.shape[1], 3))
AttributeError: 'NoneType' object has no attribute 'resize'
```

## EXPECTED RESULTS

期待される結果

```
INFO: CONVERT
_____ Downloading images for: ドーベルマン窃盗 ...
INFO: COUNT
INFO: EMIT COLOR COUNT
```

## NOTE

- [x] サポートされていない形式のpng画像を弾いてみる

**Comment by nakashimas** [comment]
## FIX

考えられる対応策

- [ ] 画像生成前に、前回生成時に残された一時ファイルを全て消す処理を追加する
- [ ] 破損したデータを飛ばす処理を追加する

## RESULTS

まだ作業中
